docker_build(
    "gfalbarracinr/server",
    ".",
    live_update=[
        sync("./src", "/app/src"),
        run("npm install", trigger=["package.json", "package-lock.json"]),
    ])

k8s_yaml('k8s/postgres-secret.yml')

k8s_yaml("k8s/deployment.yml")

k8s_yaml("k8s/postgres-deployment.yml")

k8s_yaml("k8s/service-account.yml")

k8s_resource("server", port_forwards=['3000:3000'])

k8s_resource("postgres", port_forwards=['5432:5432'])






