apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: server
        image: gfalbarracinr/server:latest
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
