FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy everything initially (Tilt will sync live updates later)
COPY . .

EXPOSE 4200

# run Angular dev server
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]